### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by ruudk** [php-memcached-dev/php-memcached#466]
PHP 8.0 will soon be released (November 26, 2020). 

Is this extension compatible?

**Comment by sodabrew** [comment]
The extension is compatible. A new version will be needed to allow PHP 8 in the packaging file, and I'll be sure to do that after testing with final RCs.

**Comment by ruudk** [comment]
@sodabrew Thanks. Would it be possible to [publish master as `devel` to PECL registry](https://pear.php.net/manual/en/guide.users.commandline.installing.php)? That would already allow others to test it with 8.0 RC's on CI.

**Comment by dzuelke** [comment]
Thanks for all the work on this @sodabrew. Looking forward to a stable release on PECL, that'll be useful to have for e.g. us at PaaSes providing the extension to customers :)

**Comment by andypost** [comment]
It builds and works with latest stable 8.0 - looks it's good time to tag new release

**Comment by mokraemer** [comment]
would be nice to have the release with php 8 support ready. Waiting for this to come.

**Comment by suyar** [comment]
```
./configure --enable-memcached-session --enable-memcached-igbinary --enable-memcached-msgpack --enable-memcached-sasl --enable-memcached-protocol
make -j 8
```
make error:
```
/usr/local/php/ext/memcached-3.1.5/php_memcached_server.c: In function 's_invoke_php_callback':
/usr/local/php/ext/memcached-3.1.5/php_memcached_server.c:66:9: error: 'zend_fcall_info' {aka 'struct _zend_fcall_info'} has no member named 'no_separation'
  cb->fci.no_separation = 1;
         ^
make: *** [Makefile:219: php_memcached_server.lo] Error 1
make: *** Waiting for unfinished jobs....
The command '/bin/sh -c docker-php-install ${PHP_EXTENSIONS}' returned a non-zero code: 2
```

But It is working find without `--enable-memcached-protocol`

**Comment by mokraemer** [comment]
any news here?

**Comment by jonathan-rosa** [comment]
@mokraemer 
> 
> 
> any news here?

If you wish to develop with it (hopefully not for production), you can try cloning master then building with php8.0-dev

**Comment by sodabrew** [comment]
Just a couple details left before I put out a release.

**Comment by VanessaTang95** [comment]
> Just a couple details left before I put out a release - some recent PRs show you the activity to make sure that the extension throws errors in the new style and the new type checks.

Hi, is there any update about the release?

**Comment by ruudk** [comment]
Please create a tag so that we can start testing it 🙏

**Comment by FlintMayers** [comment]
Any progress?

**Comment by mokraemer** [comment]
ping...

**Comment by PirxDanford** [comment]
We had been blissfully ignorant of the missing support and our acceptance test scenarios with PHP 8 had been using memcached. This explains the weird random session loss that we had been facing.
Also - Ping ;-)

**Comment by mokraemer** [comment]
any news?

**Comment by aran112000** [comment]
We're now less than 1 month away from PHP 8.1's release and it doesn't appear there's been a release of memcached in nearly 2 years (2019-12-03). 

Are there any maintainers for this project that could tag a BETA release in the current state for a PECL release? I see earlier this year @remicollet has merged in some fixes for PHP 8.1 already.

**Comment by remicollet** [comment]
3.2.0RC1 s released

**Comment by sodabrew** [comment]
Thank you @remicollet!
