### ISSUE TITLE
Installing memcached in php 7.3.0-dev with ZTS

### ISSUE THREAD

**Issue by davemccall** [php-memcached-dev/php-memcached#378]
I can't install memcached extension.

I have two php executables installed on ubuntu 17. One is at /etc/php/7.0 and the other at /etc/php/7.0zts. Memcached works fine for the non-zts version. It was installed via apt-get. I manually compiled the second version with ZTS support so I could run pthreads. When I go through the following steps to install, I can't get it to work.

sudo git clone https://github.com/php-memcached-dev/php-memcached.git
cd php-memcached
sudo git checkout php7
sudo /etc/php/7.0zts/bin/phpize
sudo ./configure --with-php-config=/etc/php/7.0zts/bin/php-config
sudo make

/bin/bash /home/ubuntu/php-memcached/libtool --mode=compile cc -I/etc/php/7.0zts/include/php    -I. -I/home/ubuntu/php-memcached -DPHP_ATOM_INC -I/home/ubuntu/php-memcached/include -I/home/ubuntu/php-memcached/main -I/home/ubuntu/php-memcached -I/etc/php/7.0zts/include/php -I/etc/php/7.0zts/include/php/main -I/etc/php/7.0zts/include/php/TSRM -I/etc/php/7.0zts/include/php/Zend -I/etc/php/7.0zts/include/php/ext -I/etc/php/7.0zts/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O0 -I/etc/php/7.0zts/include/php -I/etc/php/7.0zts/include/php/main -I/etc/php/7.0zts/include/php/TSRM -I/etc/php/7.0zts/include/php/Zend -I/etc/php/7.0zts/include/php/ext -I/etc/php/7.0zts/include/php/ext/date/lib   -c /home/ubuntu/php-memcached/php_memcached.c -o php_memcached.lo
 cc -I/etc/php/7.0zts/include/php -I. -I/home/ubuntu/php-memcached -DPHP_ATOM_INC -I/home/ubuntu/php-memcached/include -I/home/ubuntu/php-memcached/main -I/home/ubuntu/php-memcached -I/etc/php/7.0zts/include/php -I/etc/php/7.0zts/include/php/main -I/etc/php/7.0zts/include/php/TSRM -I/etc/php/7.0zts/include/php/Zend -I/etc/php/7.0zts/include/php/ext -I/etc/php/7.0zts/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O0 -I/etc/php/7.0zts/include/php -I/etc/php/7.0zts/include/php/main -I/etc/php/7.0zts/include/php/TSRM -I/etc/php/7.0zts/include/php/Zend -I/etc/php/7.0zts/include/php/ext -I/etc/php/7.0zts/include/php/ext/date/lib -c /home/ubuntu/php-memcached/php_memcached.c  -fPIC -DPIC -o .libs/php_memcached.o
/home/ubuntu/php-memcached/php_memcached.c: In function ‘php_memc_printable_func’:
/home/ubuntu/php-memcached/php_memcached.c:454:25: warning: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘zend_string * {aka struct _zend_string *}’ [-Wformat=]
   spprintf (&buffer, 0, "%s::%s", ZSTR_VAL(fci->object->ce->name), fci_cache->function_handler->common.function_name);
                         ^
/home/ubuntu/php-memcached/php_memcached.c: In function ‘zim_Memcached___construct’:
/home/ubuntu/php-memcached/php_memcached.c:1282:20: error: lvalue required as left operand of assignment
   GC_REFCOUNT(&le) = 1;
                    ^
/home/ubuntu/php-memcached/php_memcached.c: In function ‘s_stat_execute_cb’:
/home/ubuntu/php-memcached/php_memcached.c:2640:24: warning: field precision specifier ‘.*’ expects argument of type ‘int’, but argument 4 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
  spprintf (&buffer, 0, "%.*s", value_length, value);
                        ^
Makefile:194: recipe for target 'php_memcached.lo' failed
make: *** [php_memcached.lo] Error 1

I've looked here and I can't seem to find anything that helps: 
https://github.com/php-memcached-dev/php-memcached/issues/218

**Comment by sodabrew** [comment]
Please do submit a PR for changes in PHP 7.3-dev, as I have not yet begun loooking at API changes there.

If you are using this module for a production server, I advise PHP 7.2 which is fully supported.

**Comment by bojanpog** [comment]
Hello!

Same error still after PHP 7.3 final is out. Does anyone has a patch for that?

Thanks, Bojan

**Comment by salvor-hardin** [comment]
Same issue happening here

also not working (it worked ok with 7.2.x) =>

pecl install memcached

**Comment by bojanpog** [comment]
Hello!

I've then successfully compiled Master branch without a problem, not php7 branch as I used to for PHP7.0-PHP7.2

BR, Bojan

**Comment by salvor-hardin** [comment]
This is with PHP 7.3.0 released 6th December.

Can you post more info where to get the file(S) ? Thanks.

**Comment by sodabrew** [comment]
The release is not posted yet. I'm trying to move one of the dependencies forward ([msgpack](https://github.com/msgpack/msgpack-php#124) serialization) otherwise will relnote that it's unsupported at this time.

**Comment by salvor-hardin** [comment]
I can confirm this works ok :


wget -N https://github.com/php-memcached-dev/php-memcached/archive/master.zip
unzip master.zip
cd php-memcached-master
phpize
make -j `cat /proc/cpuinfo | grep processor | wc -l`
make install



I can confirm that
pecl install memcached
and
pecl install msgpack

Bring compiling errors.

**Comment by bscheshirwork** [comment]
any news?

**Comment by mikechip** [comment]
Still problematic

**Comment by neoacevedo** [comment]
Only the master branch seems to work,

**Comment by sodabrew** [comment]
Try the 3.1.4 release.

**Comment by neoacevedo** [comment]
@sodabrew I recently cloned the repo, after that switched to php7 branch and it caused the issue, while doing it with the master branch worked.

**Comment by sodabrew** [comment]
The php7 branch was merged to master 2 years ago, and has been released several times now along the php-memcached 3.x series!

**Comment by linbodong** [comment]
> The php7 branch was merged to master 2 years ago, and has been released several times now along the php-memcached 3.x series!
> 
> Correction: three years ago! Three years ago! What are you doing!
> 
> ![image](https://user-images.githubusercontent.com/39406/68497781-31ffd600-020a-11ea-9c0b-f1e535be1505.png)

Hahahahahahahaha

**Comment by neoacevedo** [comment]
The main guilty: https://docs.bitnami.com/aws/apps/wordpress/configuration/install-modules-php/#php7
