### PR TITLE
Fix build with PHP 7.4

### PR DESCRIPTION
**Pull request by sunpoet**
Build error on FreeBSD with PHP 7.4 RC6:
```
--- php_memcached.lo ---
/wrkdirs/usr/ports/databases/pecl-memcached/work-php74/memcached-3.1.4/php_memcached.c:3237:7: error: expected ';' after expression
        ulong key_index;
             ^
             ;
/wrkdirs/usr/ports/databases/pecl-memcached/work-php74/memcached-3.1.4/php_memcached.c:3237:2: error: use of undeclared identifier 'ulong'
        ulong key_index;
        ^
/wrkdirs/usr/ports/databases/pecl-memcached/work-php74/memcached-3.1.4/php_memcached.c:3237:8: error: use of undeclared identifier 'key_index'
        ulong key_index;
              ^
/wrkdirs/usr/ports/databases/pecl-memcached/work-php74/memcached-3.1.4/php_memcached.c:3250:49: error: use of undeclared identifier 'key_index'
        ZEND_HASH_FOREACH_KEY_VAL(Z_ARRVAL_P(options), key_index, key, value) {
                                                       ^
/wrkdirs/usr/ports/databases/pecl-memcached/work-php74/memcached-3.1.4/php_memcached.c:3255:44: error: use of undeclared identifier 'key_index'
                        if (!php_memc_set_option(intern, (long) key_index, value)) {
                                                                ^
5 errors generated.
*** [php_memcached.lo] Error code 1
```

### CODE REVIEW

**Comment by sodabrew** [comment]
Thank you!

**Comment by fluffykhv** [comment]
There should be "long" instead of "zend_ulong" to avoid type conversion and possible uint64_t -> int32_t misuse

**Comment by sodabrew** [comment]
I think this is correct. For example this Zend code using `zend_ulong`:

https://github.com/php/php-src/blob/f7c44ef2a0e1e1e5bed5527b8899c66b00416f43/Zend/zend_objects.c#L238-L251

**Comment by fluffykhv** [comment]
but in your code used pure long as function parameter:
int php_memc_set_option(php_memc_object_t *intern, long option, zval *value)
