### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by fabiang** [php-memcached-dev/php-memcached#408]
Please make this extension compile with PHP7.3.

Current error with latest RC is:

```
php_memcached.c: In function 'zim_Memcached___construct':
php_memcached.c:1284:20: error: lvalue required as left operand of assignment
   GC_REFCOUNT(&le) = 1;
```

**Comment by NoiseByNorthwest** [comment]
You must currently checkout master, the patch is not yet released. https://github.com/php-memcached-dev/php-memcached/commit/8bfdbcc9063dafcb25fdb1d1705e07ee027d7379

**Comment by sodabrew** [comment]
PHP 7.3 isn't GA yet, but it is getting into late betas, so I'll see about
getting a release out for public use with the betas or at least 7.3-rc's.

**Comment by andrerom** [comment]
@sodabrew anything we can help with for getting a 3.1.0RC1 out? Like:
- Help review open PR's?
- For your own open PR, you need someone to take over for rebase on that?

**Comment by ryandesign** [comment]
PHP 7.3.0 final is out. Can you make a new release of php-memcached now?

**Comment by sodabrew** [comment]
Yep, I saw the release. I've been trying to get some of the dependencies updates, in particular https://github.com/msgpack/msgpack-php but nobody's home there. I suppose I can just make this a release note.

**Comment by mokraemer** [comment]
would be great if you have a least a alpha/beta release, so I can prepare the packages for distro release.

**Comment by hswong3i** [comment]
Before an alpha/beta/stable release, here my dirty workaround for Docker + PHP >= 7.0 + memcached master (https://github.com/alvistack/docker-php/blob/2f6efbd1a024c7a8288d33a0315ed58b1fc2907f/Dockerfile#L86, see https://docs.docker.com/samples/library/php/#other-extensions for more information):

```
# Install memcached
RUN set -ex \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y libmemcached-dev \
    && rm -rf /var/lib/apt/lists/* \
    && MEMCACHED="`mktemp -d`" \
    && curl -skL https://github.com/php-memcached-dev/php-memcached/archive/master.tar.gz | tar zxf - --strip-components 1 -C $MEMCACHED \
    && docker-php-ext-configure $MEMCACHED \
    && docker-php-ext-install $MEMCACHED \
    && rm -rf $MEMCACHED
```

For Docker + PHP 5.6 + memcached 2.2.0 (https://github.com/alvistack/docker-php/blob/1ee6ee8fd4576d245e570cbd3a8010d57347f026/Dockerfile#L85):
```
# Install memcached
RUN set -ex \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y libmemcached-dev \
    && rm -rf /var/lib/apt/lists/* \
    && pecl install -f memcached-2.2.0 \
    && docker-php-ext-enable memcached.so```

**Comment by Genert** [comment]
This seems to be blocker on upgrading from 7.2 to 7.3 as well.

Keeping eye on this.

Anyhow, how can I help?

**Comment by sodabrew** [comment]
Thanks everyone for your patience, I'll get a release out before the new year. Have a few high priority things of my own to get done before I declare holidays deploy blackout at the day job!

**Comment by andrerom** [comment]
Thanks @sodabrew, btw msgpack for 7.3 is out now: https://pecl.php.net/package-info.php?package=msgpack&version=2.0.3

**Comment by sodabrew** [comment]
memcached 3.1.0 is released!
https://pecl.php.net/package-changelog.php?package=memcached&release=3.1.0

**Comment by tvlooy** [comment]
@sodabrew I get this error when installing it:

```
$ pecl install -f memcached-3.1.0
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
pecl/memcached can optionally use PHP extension "igbinary" (version >= 2.0)
pecl/memcached can optionally use PHP extension "msgpack" (version >= 2.0)
downloading memcached-3.1.0.tgz ...
Starting to download memcached-3.1.0.tgz (82,407 bytes)
....................done: 82,407 bytes
15 source files, building
running: phpize
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
libmemcached directory [no] : 
zlib directory [no] : 
use system fastlz [no] : 
enable igbinary serializer [no] : 
enable msgpack serializer [no] : 
enable json serializer [no] : 
enable server protocol [no] : 
disable sasl [no] : 
disable sessions [no] : 
building in /tmp/pear/temp/pear-build-tvlQq3wM0/memcached-3.1.0
running: /tmp/pear/temp/memcached/configure --with-php-config=/usr/local/php-7.2-latest/bin/php-config --with-libmemcached-dir=no --with-zlib-dir=no --with-system-fastlz=no --enable-memcached-igbinary=no --enable-memcached-msgpack=no --enable-memcached-json=no --enable-memcached-protocol=no --disable-memcached-sasl=no --disable-memcached-session=no
configure: error: invalid feature name: memcached-sasl=no
```

**Comment by sodabrew** [comment]
Discussed in #416 and already posted 3.1.1.

**Comment by tvlooy** [comment]
great :) And congrats with the release!

**Comment by OskarStark** [comment]
Thank you 🎉

**Comment by PierreGranger** [comment]
Hi,

Not sure this is a solution but you can use memcached 3.1.3 with php 7.3 on docker :

```
RUN apt-get update
RUN apt-get install -y git libmemcached-dev wget unzip
RUN apt-get install --no-install-recommends -y libzip-dev zlibc zlib1g
RUN docker-php-ext-configure zip --with-libzip
RUN docker-php-ext-install zip

RUN mkdir -p /usr/src/php/ext/memcached
WORKDIR /usr/src/php/ext/memcached
RUN wget https://github.com/php-memcached-dev/php-memcached/archive/v3.1.3.zip; unzip /usr/src/php/ext/memcached/v3.1.3.zip
RUN mv /usr/src/php/ext/memcached/php-memcached-3.1.3/* /usr/src/php/ext/memcached/

RUN docker-php-ext-configure memcached && docker-php-ext-install memcached 
```
